version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - bot
