server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Opciones de compresión para servir más rápido
    gzip on;
    gzip_types text/css application/javascript application/json application/font-woff application/font-tff image/gif image/png image/jpeg application/octet-stream;

    # Bloque principal para React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché en el navegador para archivos estáticos de Vite (Assets como js, css, woff, png...)
    location ~* \.(?:css|js|map|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff2|woff)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Denegar archivos ocultos como .env o .git si por error existen
    location ~ /\. {
        deny all;
    }
}
